FROM python:latest
ADD ./ /home/
WORKDIR /home/practica_big_data_2019
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install joblib
WORKDIR /home/practica_big_data_2019/resources/web
EXPOSE 5000
